version: '2'

services:
  conanexiles:
    image: alinmear/docker-conanexiles
    restart: always
    environment:
        - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=temp_pass"
        - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName='RP Trucks only"
        - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=temp_pass"
    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
    volumes:
        - data:/conanexiles
  netdata:
    image: netdata/netdata
    ports:
        - 19999:19999
    cap_add:
        - SYS_PTRACE
    security_opt:
        - apparmor:unconfined
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
    data:
        driver: local